version: 2 # use CircleCI 2.0
jobs:
  build:
    working_directory: ~/keycloak-lambda-authorizer # directory where steps will run

    docker: # run the steps with Docker
      - image: circleci/node:12.16.1 # ...with this image as the primary container; this is where all `steps` will run

    steps: # a collection of executable commands

      - checkout # check out source code to working directory

      - run:
          name: build source
          command: npm i && cd keycloak-cloudfront-dynamodb && npm i
      - run:
          name: lint
          command: npm run lint
      - run:
          name: test
          command: npm run test
      - run:
          name: publish coveralls
          command: node ./node_modules/coveralls/bin/coveralls.js < .coverage/lcov.info
      - store_artifacts:
          path: .coverage
      - run:
          name: build example/keycloak-authorizer serverless
          command: cd example/keycloak-authorizer/serverless && npm i
      - run:
          name: lint example/keycloak-authorizer serverless
          command: cd example/keycloak-authorizer/serverless && npm run lint
      - run:
          name: build example/keycloak-authorizer serverless-jwks
          command: cd example/keycloak-authorizer/serverless-jwks && npm i
      - run:
          name: lint example/keycloak-authorizer serverless-jwks
          command: cd example/keycloak-authorizer/serverless-jwks && npm run lint
      - run:
          name: build example/keycloak-authorizer ui
          command: cd example/keycloak-authorizer/ui && npm i
      - run:
          name: lint example/keycloak-authorizer ui
          command: cd example/keycloak-authorizer/ui && npm run lint
      - run:
          name: build example/keycloak-cloudfront cloudfront-cdk
          command: cd example/keycloak-cloudfront/keycloak-cloudfront-cdk && npm i
      - run:
          name: build example/keycloak-cloudfront lambda-edge-example
          command: cd example/keycloak-cloudfront/lambda-edge-example && npm i && npm run build
      - run:
          name: build example/keycloak-cloudfront cloudfront
          command: cd example/keycloak-cloudfront && npm i && npm run build
      - run:
          name: lint example/keycloak-cloudfront cloudfront
          command: cd example/keycloak-cloudfront && npm run lint
      - run:
          name: build example/keycloak-cloudfront-portal cloudfront-cdk
          command: cd example/keycloak-cloudfront-portal/keycloak-cloudfront-cdk && npm i
      - run:
          name: build example/keycloak-cloudfront-portal lambda-edge-example
          command: cd example/keycloak-cloudfront-portal/lambda-edge-example && npm i && npm run build
      - run:
          name: build example/keycloak-cloudfront-portal cloudfront
          command: cd example/keycloak-cloudfront-portal && npm i && npm run build
      - run:
          name: lint example/keycloak-cloudfront-portal cloudfront
          command: cd example/keycloak-cloudfront-portal && npm run lint
      - run:
          name: lint example/chain-service-calls/frontend
          command: cd example/chain-service-calls/frontend && npm i && npm run lint
      - run:
          name: lint example/chain-service-calls/service1
          command: cd example/chain-service-calls/service1 && npm i && npm run lint
      - run:
          name: lint example/chain-service-calls/service2
          command: cd example/chain-service-calls/service2 && npm i && npm run lint
      - run:
          name: lint example/chain-service-calls/service3
          command: cd example/chain-service-calls/service3 && npm i && npm run lint
      - run:
          name: lint example/express/frontend
          command: cd example/express/frontend && npm i && npm run lint
      - run:
          name: lint example/express/express-service
          command: cd example/express/express-service && npm i && npm run lint
      - run:
          name: lint example/express-scopes/frontend
          command: cd example/express-scopes/frontend && npm i && npm run lint
      - run:
          name: lint example/express-scopes/express-service
          command: cd example/express-scopes/express-service && npm i && npm run lint
      - run:
          name: lint example/userToAdminAPI/frontend
          command: cd example/userToAdminAPI/frontend && npm i && npm run lint
      - run:
          name: lint example/userToAdminAPI/express-service
          command: cd example/userToAdminAPI/express-service && npm i && npm run lint
