version: 2 # use CircleCI 2.0
jobs:
  build:
    working_directory: ~/keycloak-lambda-authorizer # directory where steps will run

    docker: # run the steps with Docker
      - image: circleci/node:12.16.1 # ...with this image as the primary container; this is where all `steps` will run

    steps: # a collection of executable commands

      - checkout # check out source code to working directory

      - run:
          name: build source
          command: npm i
      - run:
          name: lint
          command: npm run lint
      - run:
          name: test
          command: npm run test
      - run:
          name: build
          command: npm run build
      - run:
          name: publish coveralls
          command: node ./node_modules/coveralls/bin/coveralls.js < .coverage/lcov.info
      - store_artifacts:
          path: .coverage
      - run:
          name: build examples/keycloak-authorizer serverless
          command: cd examples/keycloak-authorizer/serverless && npm i
      - run:
          name: lint examples/keycloak-authorizer serverless
          command: cd examples/keycloak-authorizer/serverless && npm run lint
      - run:
          name: build examples/keycloak-authorizer serverless-jwks
          command: cd examples/keycloak-authorizer/serverless-jwks && npm i
      - run:
          name: lint examples/keycloak-authorizer serverless-jwks
          command: cd examples/keycloak-authorizer/serverless-jwks && npm run lint
      - run:
          name: build examples/keycloak-authorizer ui
          command: cd examples/keycloak-authorizer/ui && npm i
      - run:
          name: lint examples/keycloak-authorizer ui
          command: cd examples/keycloak-authorizer/ui && npm run lint
      - run:
          name: lint examples/chain-service-calls/frontend
          command: cd examples/chain-service-calls/frontend && npm i && npm run lint
      - run:
          name: lint examples/chain-service-calls/service1
          command: cd examples/chain-service-calls/service1 && npm i && npm run lint
      - run:
          name: lint examples/chain-service-calls/service2
          command: cd examples/chain-service-calls/service2 && npm i && npm run lint
      - run:
          name: lint examples/chain-service-calls/service3
          command: cd examples/chain-service-calls/service3 && npm i && npm run lint
      - run:
          name: lint examples/express/frontend
          command: cd examples/express/frontend && npm i && npm run lint
      - run:
          name: lint examples/express/express-service
          command: cd examples/express/express-service && npm i && npm run lint
      - run:
          name: lint examples/express-scopes/frontend
          command: cd examples/express-scopes/frontend && npm i && npm run lint
      - run:
          name: lint examples/express-scopes/express-service
          command: cd examples/express-scopes/express-service && npm i && npm run lint
      - run:
          name: lint examples/userToAdminAPI/frontend
          command: cd examples/userToAdminAPI/frontend && npm i && npm run lint
      - run:
          name: lint examples/userToAdminAPI/express-service
          command: cd examples/userToAdminAPI/express-service && npm i && npm run lint
